### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by paolafer**
This PR adapts the code to the latest cosmetic changes in the `nexus` core code (basically, the `Pmt` key is changed to `Sensor` in the sensitive detector classes). It also fixed the name of an environment variable and a script.

### CODE REVIEW

**Comment by paolafer** [comment]
Since this PR involves only a change of names and an important but straightforward fix in the persistency, I'll merge it without formal approval.

**Comment by carmenromo** [comment]
After this PR, when compiling I have the error: 

`source/petalo.cc:11:10: fatal error: 'nexus/NexusApp.h' file not found`

If I compile using the previous version, it works...

**Comment by paolafer** [comment]
I have tried getting a new clone and compiling from the scratch and it works for me. From the error you quote, I would say that you haven’t set correctly the environment variables to link to nexus. We can have a look at it together next week.

**Comment by carmenromo** [comment]
Yeah, it was not a problem of the PR but the paths in my computer. Sorry, I thought I had deleted the message in github!

**Pull request merged**
